# Use postgres/example user/password credentials
#version: '3.9'

#move to -> cd src/docker
#then -> docker compose up
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128M
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: pritam
      POSTGRES_PASSWORD: 9749215498
      POSTGRES_DB: pritamdb
    
    ports:
      - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  
